### ISSUE TITLE
Добавить тайные знания

### ISSUE THREAD

**Issue by ksuandi** [ksuandi/vikplan.com#2]
**TLDR**: заполнить excel-файл [(пример структуры)](https://github.com/ksuandi/vikplan.com/files/3999571/tier7.xlsx) и прислать сюда

Фактически, база знаний располагается в двух файлах:

- **[общий список знаний](https://github.com/ksuandi/vikplan.com/blob/master/src/store/db/research_list.js)** 
- **[список уровней знаний](https://raw.githubusercontent.com/ksuandi/vikplan.com/master/src/store/db/research.js)**

На самом деле, эти файлы генерируются парой запросов из таблицы БД mysql
```
CREATE TABLE `research` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `slug` varchar(15) DEFAULT NULL,
  `name` varchar(80) DEFAULT NULL,
  `level` tinyint(1) unsigned DEFAULT NULL,
  `food` bigint(1) unsigned DEFAULT NULL,
  `lumber` bigint(1) unsigned DEFAULT NULL,
  `iron` bigint(1) unsigned DEFAULT NULL,
  `stone` bigint(1) unsigned DEFAULT NULL,
  `silver` bigint(1) unsigned DEFAULT NULL,
  `gold` int(10) unsigned DEFAULT NULL,
  `time_days` int(10) unsigned DEFAULT NULL,
  `time_seconds` int(10) unsigned DEFAULT NULL,
  `effect_value` varchar(20) DEFAULT NULL,
  `effect_name` varchar(200) DEFAULT NULL,
  `oracle` tinyint(1) unsigned DEFAULT NULL,
  `req1` varchar(80) DEFAULT NULL,
  `req2` varchar(80) DEFAULT NULL,
  `req3` varchar(80) DEFAULT NULL,
  `req4` varchar(80) DEFAULT NULL,
  `inf` int(1) unsigned DEFAULT NULL,
  `scroll` mediumint(1) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3004 DEFAULT CHARSET=utf8;
```

Самый простой вариант обновить базу новыми знаниями:
1. Заполнить excel файл [(пример структуры)](https://github.com/ksuandi/vikplan.com/files/3999571/tier7.xlsx) и прислать его сюда. Этот этап самый трудоемкий.

Остальные шаги для желающих сделать полноценный pull request:
2. Сохранить его в csv
3. Распарсить csv и сгенерировать требуемую структуру json-файлов (я это делаю с помощью Mysql Workbench)

**Comment by Arsenal02** [comment]
[secretf.xlsx](https://github.com/ksuandi/vikplan.com/files/4164808/secretf.xlsx)

**Comment by RinatG** [comment]
[research_secret.xlsx](https://github.com/ksuandi/vikplan.com/files/4512981/research_secret.xlsx)
файл со всеми Тайными знаниями.
но запушить бранч нет прав, в нем есть ряд правок и доработок. см. форк

**Comment by ksuandi** [comment]
@RinatG спасибо! выложил

**Comment by RinatG** [comment]
докинул багфикс #4

**Comment by Arsenal02** [comment]
Я ещё 6ого февраля делал почти такую же таблицу, а почему-то ответа не было(

**Comment by RinatG** [comment]
> Я ещё 6ого февраля делал почти такую же таблицу, а почему-то ответа не было(

коллега, я свою таблицу сделал на основе твоей. в твоей были только крепости, я добавил Нападение и Оборону. и вот только сейчас дошли руки сделать полноценную доработку, чтобы новые знания на сайте могли появится. спасибо тебе!

**Comment by Arsenal02** [comment]
@ksuandi там можно сделать ещё и 2, 3 лвл тайных веток, по возможности) я даже дам коэффициенты знаний)
Осколки:
1 лвл (х)
2 лвл (3,3х)
3 лвл (11,7х)
Голда:
1 лвл (х)
2 лвл (7,62х)
3 лвл (45х)
Ускоры:
1 лвл (х)
2 лвл (3,3х)
3 лвл (11,7х)
Могущество:
1 лвл (х)
2 лвл (3,3х)
3 лвл (11,7х)

**Comment by RinatG** [comment]
> там можно сделать ещё и 2, 3 лвл тайных веток, по возможности) я даже дам коэффициенты знаний)
у меня есть это в планах. я еще не придумал, как это удобнее хранить и показывать. но в планах точно сделаю. за коэффициенты спасибо!
P.S. @ksuandi отошел от дел, я так понял, так что состав сайта теперь на совести сообщества.

**Comment by Arsenal02** [comment]
@RinatG я помню, что он отошёл, но мне было интересно, как теперь заполнять сайт... одно дело GitHub, но другое дело, что нет доступа к самому сайту, куда всё это загружать... или я слепой и пока плохо разбираюсь в GitHub

**Comment by RinatG** [comment]
@Arsenal02 мы заливаем сюда, а @ksuandi обновляет сайт. Надеюсь, это не слишком много хлопот ему доставляет, а то я уже купил домен vikplan2.ru на всякий случай :)

**Comment by ksuandi** [comment]
планы такие: домен vikplan.com истекает где-то в ноябре, и продлевать его не планирую. оставлю крутиться на vikplan.web.app (бесплатный firebase hosting). так что думайте.

насчет ru-домена - вдруг кто-нибудь захочет добавить другие языки? я бы оставил что-то более универсальное. так-то визиты есть со всех континентов (кроме антарктиды - не доработал маленько плариум с пингвинами).

ну и еще бы посоветовал оставить вашу обратную связь на сайте. я поставил линк на гитхаб, но это прямо скажем не для всех. а так будут какие-нибудь идеи/замечания/благодарности. хоть какая-то награда за старания

**Comment by Arsenal02** [comment]
ну, возможно, перевести всё можно будет, есть же на английском все термины, разве только инструкцию как-то проработать, а остальные названия просто заменять... обратная связь - ну, у меня есть VK, Telegram, номер, конечно, тоже есть, но вряд ли выкладывать буду) если надо, могу кинуть, всё равно есть идеи по улучшению платформы ещё

**Comment by Arsenal02** [comment]
@RinatG кстати, ты же знаешь сайт vikings.help? надо подсмотреть, как они там сделали уровни веток валькирий, и сделать подобное уже на викплане, но с сохранением, как и все остальные знания...
Плюс, я заметил, что уже давно есть знания антитиров, но в статистике знаний они до сих пор не отображаются... антитипы да, статы да, антитиры нет... да и теперь уже делится на нападение, оборону и крепости, тоже это тогда надо будет предусматривать... кароче, работы много)

**Comment by RinatG** [comment]
> кстати, ты же знаешь сайт vikings.help? надо подсмотреть, как они там сделали уровни веток валькирий

да, примерно так и нужно будет делать

> давно есть знания антитиров, но в статистике знаний они до сих пор не отображаются

добавляется технически не сложно, но в текущей версии только руками в коде (хлопотно). я уже думал, как бы эти данные хранить в базе (табл. `research`), чтобы в любой момент можно было из нее перегенерировать `research.js` и `research_list.js`.

одним словом, планов много. нужно их структурировать и найти время на реализацию.
текущий FR, полагаю, можно закрывать.
