### ISSUE TITLE
Разрешить выбирать и сохранять уровень стоимости улучшений Тайных знаний

### ISSUE THREAD

**Issue by RinatG** [ksuandi/vikplan.com#5]
Необходимо добавить инструмент для выбора уровня стоимости в трех ветках Тайных знаний.
Уровень должен сохраняться в текущую прокачку и влиять на стоимости с учетом коэффициентов:

1. Осколки:

- 1 лвл (х)
- 2 лвл (3,3х)
- 3 лвл (11,7х)

2. Голда:

- 1 лвл (х)
- 2 лвл (7,62х)
- 3 лвл (45х)

3. Ускоры:

- 1 лвл (х)
- 2 лвл (3,3х)
- 3 лвл (11,7х)

4. Могущество:

- 1 лвл (х)
- 2 лвл (3,3х)
- 3 лвл (11,7х)

**Comment by Arsenal02** [comment]
@RinatG сейчас появилась у меня не без помощи некоторых идея, как реализовать уровни тайных знаний... Если помнишь, в расчётах стоимости знаний и стройки есть разделы бонусов скинов, титулов и прочее, и всё это потом накладывается на ускоры... можно подобное будет легко встроить для стоимости тайных знаний

**Comment by RinatG** [comment]
реализовано в #7

**Comment by ksuandi** [comment]
@RinatG давай к тебе реп перенесем?

**Comment by Arsenal02** [comment]
Мне всё-таки кажется, надо добавить в будущем на сайт Оплот Валькирий, Асов, VIP, Достижения, хоть это и кажется банальным и ненужным - без этого тогда подсчёт стат в обзоре знаний выглядит неполным, также надо добавить подсчёт параметры урона, защиты и здоровья против тиров. Я лично вижу сайт как полноценный путеводитель по прокачке игрока, куда можно будет занести буквально всю прокачку игрока

**Comment by RinatG** [comment]
> Мне всё-таки кажется, надо добавить в будущем на сайт Оплот Валькирий, Асов, VIP, Достижения, хоть это и кажется банальным и ненужным - без этого тогда подсчёт стат в обзоре знаний выглядит неполным, также надо добавить подсчёт параметры урона, защиты и здоровья против тиров. Я лично вижу сайт как полноценный путеводитель по прокачке игрока, куда можно будет занести буквально всю прокачку игрока

добавить можно, но оно не будет иметь завершенного смысла, пока к каждому бонусу не будут указаны условия срабатывания (нападение/оборона, крепость/город, классы, тиры). сейчас я вижу это очень объемной работой. хочется, но руки не доходят. даже текущая обобщенная табличка с учетом множества обновлений игры уже не отражает полную реальность. так что бэклог тут необъятный :) но мы его съедим по частям, уверен!

**Comment by RinatG** [comment]
> @RinatG давай к тебе реп перенесем?

без переноса CI/CD ко мне какой смысл? с учетом твоих планов по поводу домена нам с тобой еще нужно будет поработать :)
